Implementing counter of remaining bombs
arkivanov/Minesweeper pull request #11
Opened 2024-02-27 21:07 UTC by b0r1ngx

Want to add some things to your repository, one of it counter of remaining bombs.

Can u check code (for correct usage, code-style) and approve to add these features

Reference (upper-left corner): 
<img width="334" alt="image" src="https://github.com/arkivanov/Minesweeper/assets/55315908/fd019171-be40-4793-916a-982a283e782d">

2024-02-27 21:33 UTC, arkivanov requested changes

2024-02-27 21:33 UTC, arkivanov commented on composeApp/src/commonMain/kotlin/com/arkivanov/minesweeper/game/GameContent.kt
> +        state.maxMines - grid.values.count { it.status.isFlagged }
Let's make it an extension, something like `val GameState.remainingMines: Int get() = ...`, and put it in `GameState.kt` file. The name `remainingMines` would be consistent with `maxMines`.

2024-02-27 21:33 UTC, arkivanov commented on composeApp/src/commonMain/kotlin/com/arkivanov/minesweeper/game/GameContent.kt
> +                        40.dp,
It would be nice to add the argument name for `40.dp`.

2024-02-27 21:33 UTC, arkivanov commented on composeApp/src/commonMain/kotlin/com/arkivanov/minesweeper/game/GameContent.kt
> +                                    modifier = Modifier
This change looks irrelevant to the PR. Revert?

2024-02-27 21:33 UTC, arkivanov commented on composeApp/src/commonMain/kotlin/com/arkivanov/minesweeper/game/GameContent.kt
> +import androidx.compose.foundation.layout.*
Please don't use wildcard imports. You can disable it in the IDE settings.

2024-02-27 21:40 UTC, arkivanov commented
Could you please also attach a screenshot? I'm curious how it looks like?

2024-02-27 22:04 UTC, b0r1ngx commented
> Could you please also attach a screenshot? I'm curious how it looks like?

im thinking about how to do it right:
1) leave RestartButton at center, and place counter lefty from it
2) or make how i make it with Row, because in next iteration i'm also want to add a stopwatch

2024-02-27 22:09 UTC, arkivanov commented
It would be nice to keep the reset button centered. Both counters can have weight=1 and horizontally centered text.

2024-02-27 22:14 UTC, b0r1ngx commented
done, please check @arkivanov

2024-02-27 22:15 UTC, b0r1ngx commented
> It would be nice to keep the reset button centered. Both counters can have weight=1 and horizontally centered text.

not saw, this message, think to update for it, wait please:c

2024-02-27 22:32 UTC, b0r1ngx commented
@arkivanov not so perfect, but its start looks like that
<img width="801" alt="image" src="https://github.com/arkivanov/Minesweeper/assets/55315908/1882e958-16cc-4325-98fe-5583f79274b4">

2024-02-28 14:56 UTC, arkivanov commented
Thanks! I will add proper assets (images) a bit later and then we can update the design.

2024-02-28 14:56 UTC, arkivanov approved these changes

2024-02-28 14:56 UTC, merged

2024-02-28 15:29 UTC, arkivanov commented
I've added digit icons, see #13.

2024-02-28 17:13 UTC, b0r1ngx commented
> I've added digit icons, see #13.

Yea, i've checked it out, it looks awesome.

When I tried this repo in the game and started implementing counter - I thought that it was good to add some fonts to stylise the app more as classic. Which approach is `better` (subjective, how do you think?):
- to use images
- or fonts 
in some cases or for some things?

I'd also like to use images in this case because we use only [0-9-]:)

2024-02-28 17:40 UTC, arkivanov commented
Since this project resembles the original Win9x Minesweeper design, it would be good to use the digit images. We can convert numbers to strings padded with zeros (taking special care for negative numbers), and then just through chars and render digit images.

2024-02-28 17:51 UTC, b0r1ngx commented
> Since this project resembles the original Win9x Minesweeper design, it would be good to use the digit images. We can convert numbers to strings padded with zeros (taking special care for negative numbers), and then just iterate through chars and render digit images.

Yea, I understand how to work in many ways, now trying to understand how implement it here as good as possible, first sketch looks like.. 
<img width="1200" alt="image" src="https://github.com/arkivanov/Minesweeper/assets/55315908/06ef1763-c291-4d9f-8c4a-a6994cf284c4">

(trying to understand why Compose Images, increase their sizes like a square-shaped thing, even using .height instead of .size modifiers, but I think that I try to solve it myself)

2024-02-28 18:14 UTC, arkivanov commented
I think we need to set width and height explicitly for every image. It should be the same as the actual size of the images.