Implemented things by branch name, also:
arkivanov/Minesweeper pull request #14
Opened 2024-02-28 18:35 UTC by b0r1ngx

1) Created setContentDescription modifier that allows to set contentDescription on any used Modifier - as accessibility feature, suppossing that it may help to understand the UI architecture more

2024-02-28 18:37 UTC, b0r1ngx commented
To understand how it looks like, attach few screenshots:
When start a game:
![image](https://github.com/arkivanov/Minesweeper/assets/55315908/27b934f1-d6a4-4bdb-9f14-6df3c3eccf5c)

when user mark more than max of the mines:
![image](https://github.com/arkivanov/Minesweeper/assets/55315908/4bf109ae-96d0-4277-b574-396162b00d16)

2024-02-28 18:40 UTC, b0r1ngx commented
@arkivanov Hello, please, check how it looks like!

2024-02-28 21:35 UTC, arkivanov requested changes

2024-02-28 21:35 UTC, arkivanov commented on composeApp/src/commonMain/kotlin/com/arkivanov/minesweeper/game/GameState.kt
> +// TODO: Can we somehow increase work of this thing? not each time count run for all grid
Let's change the TODO text to something like "Consider making this a part of the state"

2024-02-28 21:35 UTC, arkivanov commented on composeApp/src/commonMain/kotlin/com/arkivanov/minesweeper/ComposeUtils.kt
> +fun Modifier.setContentDescription(description: String, role: Role): Modifier =
Let's name it as `semantics`.

2024-02-28 21:35 UTC, arkivanov commented on composeApp/src/commonMain/kotlin/com/arkivanov/minesweeper/game/GameContent.kt
> +fun RemainingMines(
I think we can leverage the `padStart` function and do something as follows. This `Counter` function could be reused in both cases - remaining mine counter and (future) time counter.

```kotlin
@Composable
private fun Counter(value: Int, modifier: Modifier = Modifier) {
    Row(modifier = modifier, horizontalArrangement = Arrangement.Center) {
        value.toCounterString().forEach { char ->
            Image(
                modifier = Modifier.size(width = 13.dp, height = 23.dp),
                painter = LocalGameIcons.icons.digits.getValue(char),
                contentDescription = char.toString(),
            )
        }
    }
}

private fun Int.toCounterString(): String =
    if (this >= 0) {
        coerceAtMost(999).toString().padStart(length = COUNTER_LENGTH, padChar = '0')
    } else {
        "-" + coerceAtLeast(-99).absoluteValue.toString().padStart(length = COUNTER_LENGTH - 1, padChar = '0')
    }
```

2024-02-28 21:35 UTC, arkivanov commented on composeApp/src/commonMain/kotlin/com/arkivanov/minesweeper/game/GameContent.kt
> +                    modifier = Modifier.height(26.dp),
Let's define the exact size for the image as per PNGs: 13.dp x 23.dp

2024-02-28 21:35 UTC, arkivanov commented on composeApp/src/commonMain/kotlin/com/arkivanov/minesweeper/game/GameContent.kt
> +private const val defaultCountersSize = 3
I suggest to name it as `COUNTER_LENGTH`.

2024-02-28 21:35 UTC, arkivanov commented on composeApp/src/commonMain/kotlin/com/arkivanov/minesweeper/ComposeUtils.kt
> +    this.then(
Can we just call `semantics { ... }` here?

2024-02-29 09:30 UTC, b0r1ngx commented
@arkivanov Hello, I'm made recommended changes, please, check how it looks like!

2024-03-01 11:00 UTC, arkivanov requested changes

2024-03-01 11:00 UTC, arkivanov commented on composeApp/src/commonMain/kotlin/com/arkivanov/minesweeper/game/GameContent.kt
> +                        modifier = Modifier.weight(1f).setSemantics(
Now after the changes, maybe we can just use the original `semantics` modifier? What benefits the custom function gives us?

2024-03-01 11:00 UTC, arkivanov commented on composeApp/src/commonMain/kotlin/com/arkivanov/minesweeper/game/GameContent.kt
> +                    Stopwatch(modifier = Modifier.weight(1f))
Let's just use `Counter(value = 0, modifier = Modfier.weight(1F))` here for now.

2024-03-01 12:36 UTC, b0r1ngx commented
Let's rock it!

2024-03-01 16:35 UTC, arkivanov approved these changes

2024-03-01 16:35 UTC, merged

2024-03-01 16:35 UTC, arkivanov commented
Thank you!

2024-03-01 17:30 UTC, b0r1ngx commented
> Thank you!

Thank you too, for reviewing my code and making it better together! 

Hope I will start implementing the stopwatch soon, I don't want to use additional dependencies (for educational purposes for me and project, if someone wants to research it)

Also I tried to go to wasm site from this repo, I also got amazed that you create a pipeline that automatically creates a build and publishes it to the site (you did a great work with this CI/CD)

I visit it from mobile android chrome browser, and can't click anything. is this wasm restriction for now? Or it just doesn't work because in the project clicks are used instead of touches?

2024-03-01 18:07 UTC, arkivanov commented
Yeah, Wasm on Android chrome is pretty much broken currently. Also on any browser, all mouse clicks are recognised as left clicks.